const fs=require('fs'),p=require('path');
const dir=p.join(process.env.HOME,'.claude','skills');

// ===== anime-filter =====
fs.writeFileSync(p.join(dir,'anime-filter','app.html'),
`<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>\u4E8C\u6B21\u5143\u6EE4\u955C</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{background:#0f380f;color:#8bac0f;font-family:'Courier New',Consolas,monospace;min-height:100vh;display:flex;flex-direction:column;align-items:center}.title-bar{width:100%;max-width:720px;background:#306230;border:3px solid #0f380f;border-bottom:none;padding:6px 12px;text-align:center;font-size:18px;font-weight:bold;color:#9bbc0f;text-shadow:2px 2px 0 #0f380f;margin-top:8px}.main{width:100%;max-width:720px;background:#1a4a1a;border:3px solid #306230;box-shadow:6px 6px 0 #0f380f;padding:12px;display:flex;flex-direction:column;gap:10px}.view-box{position:relative;width:100%;background:#000;border:3px solid #306230;overflow:hidden}.view-box canvas{width:100%;display:block}.fps{position:absolute;top:6px;right:6px;background:rgba(15,56,15,.8);color:#8bac0f;font-size:10px;padding:2px 6px;border:1px solid #306230}.filter-row{display:flex;gap:6px;flex-wrap:wrap}.fbtn{background:#306230;color:#8bac0f;border:3px solid #0f380f;box-shadow:3px 3px 0 #0f380f;font-family:monospace;font-size:12px;font-weight:bold;padding:6px 10px;cursor:pointer;flex:1;min-width:60px;text-align:center}.fbtn:hover{background:#8bac0f;color:#0f380f}.fbtn.active{background:#8bac0f;color:#0f380f;transform:translate(2px,2px);box-shadow:1px 1px 0 #0f380f}.panel{background:#0f380f;border:2px solid #306230;padding:8px}.panel label{display:flex;align-items:center;gap:6px;font-size:11px;color:#306230;margin:3px 0}.panel input[type=range]{width:120px;accent-color:#8bac0f}.btn-row{display:flex;gap:6px;flex-wrap:wrap}button{background:#8bac0f;color:#0f380f;border:3px solid #0f380f;box-shadow:4px 4px 0 #306230;font-family:monospace;font-size:12px;font-weight:bold;padding:6px 12px;cursor:pointer}button:hover{background:#9bbc0f;transform:translate(2px,2px);box-shadow:2px 2px 0 #306230}button:active{transform:translate(4px,4px);box-shadow:none}video{display:none}</style></head>
<body><div class="title-bar">\u2605 \u4E8C\u6B21\u5143\u6EE4\u955C \u2605</div><div class="main">
<div class="view-box"><canvas id="out"></canvas><div id="fps" class="fps">0 FPS</div></div>
<div class="filter-row"><div class="fbtn active" onclick="setF(0,this)">\u8D5B\u7490\u73DE</div><div class="fbtn" onclick="setF(1,this)">\u50CF\u7D20\u98CE</div><div class="fbtn" onclick="setF(2,this)">\u65B0\u6D77\u8BDA</div><div class="fbtn" onclick="setF(3,this)">\u6F2B\u753B</div><div class="fbtn" onclick="setF(4,this)">\u6C34\u5F69</div></div>
<div class="panel"><label>\u8FB9\u7F18\u5F3A\u5EA6: <input type="range" id="sE" min="1" max="10" value="5"><span id="vE">5</span></label><label>\u8272\u5F69\u5C42\u7EA7: <input type="range" id="sC" min="3" max="16" value="6"><span id="vC">6</span></label><label>\u50CF\u7D20\u5927\u5C0F: <input type="range" id="sP" min="2" max="16" value="6"><span id="vP">6</span></label></div>
<div class="btn-row"><button onclick="startCam()">\u25B6 \u5F00\u542F\u6444\u50CF\u5934</button><button onclick="capture()">\u2605 \u622A\u56FE\u4FDD\u5B58</button><button onclick="showO=!showO">\u25C6 \u5BF9\u6BD4\u539F\u56FE</button></div></div>
<video id="vid" playsinline muted></video><canvas id="tmp" style="display:none"></canvas>
<script>
const vid=document.getElementById('vid'),out=document.getElementById('out'),tmp=document.getElementById('tmp');
const oCtx=out.getContext('2d'),tCtx=tmp.getContext('2d'),fpsEl=document.getElementById('fps');
let stream=null,run=false,cF=0,showO=false,eS=5,cL=6,pS=6,fc=0,lt=0;
document.getElementById('sE').oninput=function(){eS=+this.value;document.getElementById('vE').textContent=this.value};
document.getElementById('sC').oninput=function(){cL=+this.value;document.getElementById('vC').textContent=this.value};
document.getElementById('sP').oninput=function(){pS=+this.value;document.getElementById('vP').textContent=this.value};
function setF(i,el){cF=i;document.querySelectorAll('.fbtn').forEach(b=>b.classList.remove('active'));el.classList.add('active')}
async function startCam(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});vid.srcObject=stream;await vid.play();const pw=Math.min(320,vid.videoWidth),ph=Math.round(pw*vid.videoHeight/vid.videoWidth);tmp.width=pw;tmp.height=ph;out.width=pw;out.height=ph;run=true;requestAnimationFrame(loop);}catch(e){alert('\\u6444\\u50CF\\u5934\\u542F\\u52A8\\u5931\\u8D25: '+e.message)}}
function loop(t){if(!run)return;tCtx.save();tCtx.translate(tmp.width,0);tCtx.scale(-1,1);tCtx.drawImage(vid,0,0,tmp.width,tmp.height);tCtx.restore();if(showO){oCtx.drawImage(tmp,0,0)}else{const s=tCtx.getImageData(0,0,tmp.width,tmp.height);oCtx.putImageData([cel,pix,shin,mng,wc][cF](s),0,0);}fc++;if(t-lt>1000){fpsEl.textContent=fc+' FPS';fc=0;lt=t}requestAnimationFrame(loop);}
function cl(v){return v<0?0:v>255?255:Math.round(v)}
function cel(s){const w=s.width,h=s.height,d=s.data,o=new ImageData(w,h),p=o.data;const g=new Float32Array(w*h);for(let i=0;i<w*h;i++){const j=i*4;g[i]=d[j]*.299+d[j+1]*.587+d[j+2]*.114}const st=256/cL;for(let i=0;i<d.length;i+=4){p[i]=Math.round(d[i]/st)*st;p[i+1]=Math.round(d[i+1]/st)*st;p[i+2]=Math.round(d[i+2]/st)*st;p[i+3]=255}const thr=eS*15;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x;const gx=-g[i-w-1]-2*g[i-1]-g[i+w-1]+g[i-w+1]+2*g[i+1]+g[i+w+1];const gy=-g[i-w-1]-2*g[i-w]-g[i-w+1]+g[i+w-1]+2*g[i+w]+g[i+w+1];if(Math.sqrt(gx*gx+gy*gy)>thr){const j=i*4;p[j]=p[j+1]=p[j+2]=0}}return o;}
function pix(s){const w=s.width,h=s.height,d=s.data,o=new ImageData(w,h),p=o.data;const ps=pS,st=256/cL;for(let by=0;by<h;by+=ps)for(let bx=0;bx<w;bx+=ps){let r=0,g=0,b=0,c=0;for(let dy=0;dy<ps&&by+dy<h;dy++)for(let dx=0;dx<ps&&bx+dx<w;dx++){const j=((by+dy)*w+(bx+dx))*4;r+=d[j];g+=d[j+1];b+=d[j+2];c++}r=Math.round(r/c/st)*st;g=Math.round(g/c/st)*st;b=Math.round(b/c/st)*st;for(let dy=0;dy<ps&&by+dy<h;dy++)for(let dx=0;dx<ps&&bx+dx<w;dx++){const j=((by+dy)*w+(bx+dx))*4;p[j]=r;p[j+1]=g;p[j+2]=b;p[j+3]=255}}return o;}
function shin(s){const d=s.data,o=new ImageData(s.width,s.height),p=o.data;for(let i=0;i<d.length;i+=4){let r=d[i],g=d[i+1],b=d[i+2];const avg=(r+g+b)/3;r=cl(avg+(r-avg)*1.6);g=cl(avg+(g-avg)*1.6);b=cl(avg+(b-avg)*1.6);const lum=(r*.299+g*.587+b*.114)/255;if(lum>.5){r=cl(r+30*lum);g=cl(g+15*lum);b=cl(b-10*lum)}else{r=cl(r-15*(1-lum));g=cl(g+5*(1-lum));b=cl(b+35*(1-lum))}if(lum<.3){r=cl(r+10);b=cl(b+20)}p[i]=r;p[i+1]=g;p[i+2]=b;p[i+3]=255;}return o;}
function mng(s){const w=s.width,h=s.height,d=s.data,o=new ImageData(w,h),p=o.data;const g=new Float32Array(w*h);for(let i=0;i<w*h;i++){const j=i*4;g[i]=d[j]*.299+d[j+1]*.587+d[j+2]*.114}const edges=new Float32Array(w*h);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x;const gx=-g[i-w-1]-2*g[i-1]-g[i+w-1]+g[i-w+1]+2*g[i+1]+g[i+w+1];const gy=-g[i-w-1]-2*g[i-w]-g[i-w+1]+g[i+w-1]+2*g[i+w]+g[i+w+1];edges[i]=Math.sqrt(gx*gx+gy*gy);}const thr=eS*12;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,j=i*4,v=g[i];if(edges[i]>thr){p[j]=p[j+1]=p[j+2]=0}else if(v>180){p[j]=p[j+1]=p[j+2]=255}else if(v>100){const dt=((x%4<2)&&(y%4<2))?200:255;p[j]=p[j+1]=p[j+2]=dt}else if(v>60){const dt=((x%3<2)&&(y%3<2))?120:200;p[j]=p[j+1]=p[j+2]=dt}else{const dt=((x%2===0)&&(y%2===0))?40:100;p[j]=p[j+1]=p[j+2]=dt}p[j+3]=255;}return o;}
function wc(s){const w=s.width,h=s.height,d=s.data,o=new ImageData(w,h),p=o.data;const r=2,st=256/Math.max(8,cL);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let sr=0,sg=0,sb=0,c=0;const ox=((x*7+y*13)%5)-2,oy=((x*11+y*3)%5)-2;for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){const nx=Math.max(0,Math.min(w-1,x+dx+ox)),ny=Math.max(0,Math.min(h-1,y+dy+oy));const j=(ny*w+nx)*4;sr+=d[j];sg+=d[j+1];sb+=d[j+2];c++;}const j=(y*w+x)*4;let rv=Math.round(sr/c/st)*st,gv=Math.round(sg/c/st)*st,bv=Math.round(sb/c/st)*st;const avg=(rv+gv+bv)/3;p[j]=cl(rv*.85+avg*.15+10);p[j+1]=cl(gv*.85+avg*.15+8);p[j+2]=cl(bv*.85+avg*.15+5);p[j+3]=255;}return o;}
function capture(){const a=document.createElement('a');a.download='anime_'+Date.now()+'.png';a.href=out.toDataURL();a.click()}
<\\/script></body></html>`);

console.log('anime-filter OK');
